---
title: Vascular plant diversity within Howe Sound's protected areas
weight: 5
knit: (function(input, ...) { source(here::here("R/knit_render.R"), local = TRUE)$value(input, ...) })
regionField: Protected
---

## Vascular plant diversity within Howe Sound's protected areas

```{r, echo=FALSE, message=FALSE, warning=FALSE, out.width="1024px"}
#width instructions from https://stackoverflow.com/a/41371132
source("scripts/Protected_map_mapbox.R")

native.plants <- read.csv("outputs/AHSBR_native_vascular_plant_species.csv")
protected.plants <- read.csv("outputs/AHSBR_protected_native_vascular_plant_species.csv")

protectedAreaMap
protected.area.plot 
```

<div class="data-pane">
*Map 4. Protected Areas*
</div>

Based on our current knowledge, `r round(nrow(protected.plants)/nrow(native.plants)*100)` percent
of the native plant diversity known to Átl’ḵa7tsem/Howe Sound has been reported within protected areas.
While this preliminary evaluation is limited due to biases in sampling effort and other deficiencies in the data,
it represents a starting point for a more thorough assessment of progress being made toward goals of conserving our
regional habitat diversity. Please help improve our understanding of the distribution of vascular plants and other
biodiversity the region by reporting your observations to
the [Atl'ka7tsem Howe Sound Biosphere Region iNaturalist project.](https://www.inaturalist.org/projects/atl-ka7tsem-howe-sound-biosphere-region)
